### PR TITLE
add custom dns config

### PR DESCRIPTION
**Pull request by pidah**
This PR adds custom DNS config including sidecar config, updated binaries, autoscaling for kube-dns, guaranteed QOS for kubedns pods and additional logging to dnsmasq

### CODE REVIEW

**Comment by kajanth** [comment]
All good

**Comment by pidah** [comment]
@aku105 `pkg/acsengine/templates.go` contains automatically generated go code. Basically the kubernetes config yaml files (actually can handle any non-go files) are embedded into it as go code.

**Comment by aku105** [comment]
@pidah Can you add `DigitalInnovation/platform-technologies` team as Owner to this repository so that we can merge this.

**Comment by pidah** [comment]
@aku105 done.

**Pull request merged**
